version: "v2.30.3-desktop.1"


services:
  backend:
    build: ./backend
    container_name: anon_chat_backend
    ports:
      - '8000:8000'

  frontend:
    build: ./frontend
    container_name: anon_chat_frontend
    ports:
      - '5174:5174'


