version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    depends_on:
      - cache

  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - "5173:5173"

  cache:
    image: redis:latest
    container_name: cache
    ports:
      - "6379:6379"




