[tool.ruff]
line-length = 100
target-version = "py311"
exclude = ["venv", "__pycache__"]
fix = true

[tool.ruff.lint]
select = ["E", "F", "I", "N", "B", "UP", "SIM"]
ignore = ["B008"]

[tool.ruff.lint.isort]
known-first-party = ["backend"]
force-sort-within-sections = true
combine-as-imports = true